<?php

function dimfield_field_info() {
  return array(
    'dimensions' => array(
      'label' => t('Dimensions'),
      'description' => t('This field stores a height and width, and depth.'),
      'settings' => array('num_dimensions' => 2),
      'instance_settings' => array(
        'max_height' => 0,
        'max_width' => 0,
        'max_depth' => 0,
      ),
      'default_widget' => 'dimfield_combined',
      'default_formatter' => 'dimfield_default',
    ),
  );
}

function dimfield_field_schema($field) {
  if ($field['type'] == 'dimensions') {
    $schema['columns']['height'] = array(
      'type' => 'int',
      'not null' => FALSE,
    );
    $schema['columns']['width'] = array(
      'type' => 'int',
      'not null' => FALSE,
    );
    $schema['indexes'] = array(
      'height' => array('height'),
      'width' => array('width'),
    );

    if ($field['settings']['num_dimensions'] == 3) {
      $schema['columns']['depth'] = array(
        'type' => 'int',
        'not null' => FALSE,
      );
      $schema['indexes']['depth'] = array('depth');
    }

    $schema['columns']['units'] = array(
      'type' => 'varchar',
      'length' => 10,
      'not null' => FALSE,
    );

    return $schema;
  }
}