<?php

function watermark_image_effect_info() {
  $effects = array();

  $effects['watermark'] = array(
    'label' => t('Watermark'),
    'help' => t('Add a watermark to an image.'),
    'effect callback' => 'watermark_effect',
    'form callback' => 'watermark_form',
    'summary theme' => 'watermark_summary',
  );

  return $effects;
}

function watermark_form($data) {
  $form['text_color'] = array(
    '#type' => 'textfield',
    '#default_value' => (isset($data['text_color'])) ? $data['text_color'] : '#FFFFFF',
    '#title' => t('Text color'),
    '#description' => t('The color of the text to be used for this watermark. Use web-style hex colors (#FFFFFF for white, #000000 for black.'),
    '#size' => 7,
    '#maxlength' => 7,
    '#element_validate' => array('image_effect_color_validate'),
  );

  $form['text'] = array(
    '#type' => 'textfield',
    '#default_value' => (isset($data['text'])) ? $data['text'] : 'Drupal loves kittens!',
    '#title' => t('Watermakr text'),
    '#description' => t('Text to be written on the image.'),
    '#size' => 30,
    '#maxlength' => 60,
  );

  return $form;
}

function theme_watermark_summary($variables) {
  $data = $variables['data'];
  return t('with color @textcolor', array('@textcolor' => $data['text_color']));
}

function watermark_effect(&$image, $data) {
  $data['text_color'] = str_replace('#', '', $data['text_color']);
  $red = hexdec(substr($data['text_color'], 0, 2));
  $green = hexdec(substr($data['text_color'], 2, 2));
  $blue = hexdec(substr($data['text_color'], 4));

  $color = imagecolorallocate($image->resource, $red, $green, $blue);
  imagestring($image->resource, 5, 5, 5, $data['text'], $color);
}