<?php
// $Id$

define('SINGLE_BLOG_NODE_TYPE', 'article');
define('SINGLE_BLOG_LIST_COUNT', 3);

function single_blog_list($number) {
  $query = db_select('node', 'n')
    ->fields('n', array('nid', 'title', 'created', 'uid'))
    ->condition('type', SINGLE_BLOG_NODE_TYPE)
    ->condition('status', 1)
    ->orderBy('created', 'DESC')
    ->range(0, $number)
    ->addTag('node_access')
    ->execute();

  return $query;
}

function single_blog_block_info() {
  $blocks = array();

  $blocks['recent'] = array(
    'info' => t('Recent blog posts'), 
  );

  return $blocks;
}

function single_blog_block_view($delta = '') {
  $block = array('subject' => '', 'content' => '');

  if ($delta == 'recent') {
    $block['subject'] = t('Recent blog posts');

    if (user_access('access content')) {
      $results = single_blog_list(SINGLE_BLOG_LIST_COUNT);

      $items = array();
      foreach ($results as $node) {
        $items[] = array( #$items[] without a key automatically makes the key to a 0 integer
          'class' => array('node-' . $node->nid), #array(value) automatically makes the key to a 0 integer
          'data' => array(
            '#type' => 'link',
            '#title' => $node->title,
            '#href' => 'node/' . $node->nid,
          )
        );
      }

      if (!empty($items)) {
        // $block['content'] = theme('item_list', array(
        //                       'items' => $items));

        $block['content']['list'] = array(
          '#theme' => 'item_list__single_blog',
          '#items' => $items,
          '#pre_render' => array('single_blog_item_list_child_render'),
        );

        $block['content']['more'] = array(
          '#theme' => 'more_link',
          '#url' => 'blog',
          '#title' => t('Read the latest blog entries.'),
        );
      }
    }
  }

  return $block;
}

function single_blog_item_list_child_render($elements) {
  foreach (array_keys($elements['#items']) as $key) {
    if (is_array($elements['#items'][$key]['data'])) {
      $elements['#items'][$key]['data'] = 
        drupal_render($elements['#items'][$key]['data']);
    }
  }
  return $elements;
}